### ISSUE TITLE
Build fails at make

### ISSUE THREAD

**Issue by elhossary** [intel/icamerasrc#19]
Hi,
Can anybody help me to fix this?

> $ make -j8
make  all-recursive
make[1]: Entering directory '/home/muhoss/icamerasrc'
Making all in src
make[2]: Entering directory '/home/muhoss/icamerasrc/src'
Making all in interfaces
make[3]: Entering directory '/home/muhoss/icamerasrc/src/interfaces'
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall  -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils  -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security   -g -O2 -MT libgsticamerainterface_1.0_la-gstcamera3ainterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcamera3ainterface.Tpo -c -o libgsticamerainterface_1.0_la-gstcamera3ainterface.lo `test -f 'gstcamera3ainterface.cpp' || echo './'`gstcamera3ainterface.cpp
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall  -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils  -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security   -g -O2 -MT libgsticamerainterface_1.0_la-gstcameraispinterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcameraispinterface.Tpo -c -o libgsticamerainterface_1.0_la-gstcameraispinterface.lo `test -f 'gstcameraispinterface.cpp' || echo './'`gstcameraispinterface.cpp
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall  -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils  -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security   -g -O2 -MT libgsticamerainterface_1.0_la-gstcameradewarpinginterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.Tpo -c -o libgsticamerainterface_1.0_la-gstcameradewarpinginterface.lo `test -f 'gstcameradewarpinginterface.cpp' || echo './'`gstcameradewarpinginterface.cpp
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wall  -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils  -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security   -g -O2 -MT libgsticamerainterface_1.0_la-gstcamerawfovinterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcamerawfovinterface.Tpo -c -o libgsticamerainterface_1.0_la-gstcamerawfovinterface.lo `test -f 'gstcamerawfovinterface.cpp' || echo './'`gstcamerawfovinterface.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -Wall -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -g -O2 -MT libgsticamerainterface_1.0_la-gstcameraispinterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcameraispinterface.Tpo -c gstcameraispinterface.cpp  -fPIC -DPIC -o .libs/libgsticamerainterface_1.0_la-gstcameraispinterface.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -Wall -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -g -O2 -MT libgsticamerainterface_1.0_la-gstcamera3ainterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcamera3ainterface.Tpo -c gstcamera3ainterface.cpp  -fPIC -DPIC -o .libs/libgsticamerainterface_1.0_la-gstcamera3ainterface.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -Wall -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -g -O2 -MT libgsticamerainterface_1.0_la-gstcameradewarpinginterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.Tpo -c gstcameradewarpinginterface.cpp  -fPIC -DPIC -o .libs/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -std=c++11 -Wall -Werror -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -pthread -Wall -I/usr/include/libcamhal -I/usr/include/libcamhal/api -I/usr/include/libcamhal/utils -DCHROME_SLIM_CAMHAL -fstack-protector-all -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -g -O2 -MT libgsticamerainterface_1.0_la-gstcamerawfovinterface.lo -MD -MP -MF .deps/libgsticamerainterface_1.0_la-gstcamerawfovinterface.Tpo -c gstcamerawfovinterface.cpp  -fPIC -DPIC -o .libs/libgsticamerainterface_1.0_la-gstcamerawfovinterface.o
mv -f .deps/libgsticamerainterface_1.0_la-gstcamerawfovinterface.Tpo .deps/libgsticamerainterface_1.0_la-gstcamerawfovinterface.Plo
mv -f .deps/libgsticamerainterface_1.0_la-gstcameraispinterface.Tpo .deps/libgsticamerainterface_1.0_la-gstcameraispinterface.Plo
mv -f .deps/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.Tpo .deps/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.Plo
mv -f .deps/libgsticamerainterface_1.0_la-gstcamera3ainterface.Tpo .deps/libgsticamerainterface_1.0_la-gstcamera3ainterface.Plo
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2 -fPIE -fPIC -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Wl,-z,relro -Wl,-z,now -version-info 1:0:0  -o libgsticamerainterface-1.0.la -rpath /usr/lib libgsticamerainterface_1.0_la-gstcamera3ainterface.lo libgsticamerainterface_1.0_la-gstcameraispinterface.lo libgsticamerainterface_1.0_la-gstcameradewarpinginterface.lo libgsticamerainterface_1.0_la-gstcamerawfovinterface.lo -lgstbase-1.0 -lgstcontroller-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0  -lcamhal  
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib/crti.o /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/crtbeginS.o  .libs/libgsticamerainterface_1.0_la-gstcamera3ainterface.o .libs/libgsticamerainterface_1.0_la-gstcameraispinterface.o .libs/libgsticamerainterface_1.0_la-gstcameradewarpinginterface.o .libs/libgsticamerainterface_1.0_la-gstcamerawfovinterface.o   -lgstbase-1.0 -lgstcontroller-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lcamhal -L/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/crtendS.o /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib/crtn.o  -g -O2 -Wl,-z -Wl,relro -Wl,-z -Wl,now   -Wl,-soname -Wl,libgsticamerainterface-1.0.so.1 -o .libs/libgsticamerainterface-1.0.so.1.0.0
/usr/bin/ld: cannot find -lcamhal: No such file or directory
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:499: libgsticamerainterface-1.0.la] Error 1
make[3]: Leaving directory '/home/muhoss/icamerasrc/src/interfaces'
make[2]: *** [Makefile:686: all-recursive] Error 1
make[2]: Leaving directory '/home/muhoss/icamerasrc/src'
make[1]: *** [Makefile:520: all-recursive] Error 1
make[1]: Leaving directory '/home/muhoss/icamerasrc'
make: *** [Makefile:429: all] Error 2

**Comment by BingCoke** [comment]
Hi,I get same error,how I fix it?

**Comment by twouters** [comment]
> Hi,I get same error,how I fix it?

Maybe you didn't (properly) install ipu6-camera-hal before trying to build icamerasrc?

**Comment by ian-foss** [comment]
I have the same exact issue with the hal provider properly installed. @elhossary, were you able to fix this? If so, would you mind helping a fellow user. :)

**Comment by elhossary** [comment]
I could fix it but I don't why it worked, I uninstalled the HAL library and Icamerasrc, then reinstalled HAL first then icamerasrc.
That's the case on each new version

**Comment by TaylorHere** [comment]
same issue here, install by http://aur.archlinux.org/packages/icamerasrc-git
